'use client'

import { useEffect, useState } from 'react'
import { useSession } from '@/lib/session'
import { getToken } from '@/lib/api'

// The salmon membership card. Click it to flip (3D rotateY) between the
// front (member details) and the back (QR code). Front sets the height;
// the back is absolutely stacked on top and pre-rotated 180°, so the card
// keeps the same footprint whichever side is showing.
//
// The QR is what an officer scans to check somebody in. It's generated by the
// API from the member's id and never stored, so it's the same image every time
// and there's nothing to keep in sync.
//
// It's fetched rather than pointed at with a plain <img src>: the endpoint is
// behind the Authorization header like everything else, and an <img> tag can't
// send one. So the PNG comes back as a blob and the object URL goes in the src.
//
// Exported for the lab view's "show QR code" popup, which is the same code.
export function usePassQr(enabled) {
	const [src, setSrc] = useState(null)

	useEffect(() => {
		if (!enabled) return
		let url = null
		let live = true

		fetch('/api/members/me/qr', {
			headers: { Authorization: `Bearer ${getToken()}` },
		})
			.then((response) => (response.ok ? response.blob() : null))
			.then((blob) => {
				if (!blob || !live) return
				url = URL.createObjectURL(blob)
				setSrc(url)
			})
			.catch(() => {})

		// the blob stays in memory until it's let go of explicitly
		return () => {
			live = false
			if (url) URL.revokeObjectURL(url)
		}
	}, [enabled])

	return src
}

// '2026-08-24T00:00:00.000Z' -> '08/24/2026'. Read off the ISO string rather
// than through Date, which treats a bare date as UTC and can hand back the day
// before depending on the timezone.
// '?' rather than a blank tile for an account that hasn't said what to call it
// yet — signing up asks for a username and a password and nothing else.
function initials(user) {
	const first = user?.firstName?.charAt(0) ?? ''
	const last = user?.lastName?.charAt(0) ?? ''
	return (first + last).toUpperCase() || '?'
}

function passDate(value) {
	if (!value) return '—'
	const [year, month, day] = String(value).slice(0, 10).split('-')
	return `${month}/${day}/${year}`
}

function PassField({ label, value, className = '' }) {
	return (
		<div className={`
			border-1
			border-salmon-light
			px-2
			py-1
			${className}
		`}>
			<p className="
				font-vietnam
				font-semibold
				text-[13px]
				leading-tight
				text-white/80
			">
				{label}
			</p>
			<p className="
				font-handrawn
				text-[25px]
				leading-tight
				text-black
			">
				{value}
			</p>
		</div>
	)
}

export default function ElementistPass() {
	const [flipped, setFlipped] = useState(false)
	const { user } = useSession()

	// Only asked for once the card has actually been turned over — most visits
	// never flip it, and there's no reason to pull an image nobody looks at.
	const qr = usePassQr(flipped)

	return (
		<div className="[perspective:1200px] select-none">
			<div
				onClick={() => setFlipped((f) => !f)}
				className={`
					relative
					cursor-pointer
					transition-transform
					duration-[900ms]
					[transform-style:preserve-3d]
					${flipped ? '[transform:rotateY(180deg)]' : ''}
				`}
			>
				{/* FRONT.

				    The photo sits beside the details while there's room for both;
				    on a narrow card it goes above them instead and stops being a
				    fixed 240px square, because two columns inside a phone-width
				    card leaves neither one usable. */}
				<div className="
					[backface-visibility:hidden]
					bg-salmon
					rounded-[10px]
					p-4
					sm:p-6
					flex
					flex-col
					sm:flex-row
					items-center
					sm:items-stretch
					gap-4
					sm:gap-6
					shadow-[-4px_4px_9px_rgba(0,0,0,0.5)]
				">
					{/* a share of the card rather than a fixed 240px, so the photo
					    gives ground as the card narrows instead of squeezing the
					    details out. Falls back to initials until there's somewhere
					    to upload a picture to. */}
					<div className="
						bg-neutral-300
						w-full
						max-w-[240px]
						sm:w-[38%]
						aspect-square
						rounded-md
						shrink-0
						overflow-hidden
						flex
						items-center
						justify-center
					">
						{user?.profilePicture
							? <img
								src={user.profilePicture}
								alt=""
								className="
									w-full
									h-full
									object-cover
								"
							/>
							: <span className="
								font-canobis
								text-[54px]
								text-salmon-dark
								select-none
							">
								{initials(user)}
							</span>}
					</div>
					<div className="
						flex-1
						min-w-0
						w-full
						flex
						flex-col
					">
						<h3 className="
							font-starbim
							text-yellow-light
							text-lg
							sm:text-xl
							2xl:text-2xl
							text-center
							tracking-wide
							whitespace-nowrap
							[-webkit-text-stroke:0.75px_black]
						">
							ELEMENTIST PASS
						</h3>
						<PassField label="username" value={user?.username ?? '—'} />
						<PassField label="first name" value={user?.firstName || '—'} />
						<PassField label="last name" value={user?.lastName || '—'} />
						<div className="
							flex
							flex-col
							sm:flex-row
							gap-2
							sm:gap-3
							items-stretch
							sm:items-end
						">
							<PassField
								label="date joined"
								value={passDate(user?.dateJoined ?? user?.createdAt)}
								className="sm:flex-1 sm:min-w-0"
							/>
							{/* wraps rather than holding one line: the card gets narrow
							    enough at some widths that a nowrap line here is what
							    would push the whole pass out of its column */}
							<p className="
								font-beachday
								font-bold
								text-[17px]
								sm:text-[20px]
								text-salmon-med
								pb-1
								flex-1
								min-w-0
								leading-tight
								text-center
							">
								CLICK CARD FOR QR CODE
							</p>
						</div>
					</div>
				</div>

				{/* BACK */}
				<div className="
					absolute
					inset-0
					[backface-visibility:hidden]
					[transform:rotateY(180deg)]
					bg-salmon
					rounded-[10px]
					p-4
					sm:p-6
					flex
					flex-col
					items-center
					justify-center
					gap-4
					shadow-[-4px_4px_9px_rgba(0,0,0,0.5)]
				">
					{/* the QR has to stay inside the card whatever the card's height
					    is — the front is what sets that, and on a narrow screen the
					    front is much taller than it is wide.

					    White rather than the grey placeholder: a QR has to be dark
					    on light to scan, and the card's salmon isn't light enough. */}
					<div className="
						bg-white
						w-[225px]
						max-w-full
						max-h-[60%]
						aspect-square
						rounded-md
						overflow-hidden
						flex
						items-center
						justify-center
					">
						{qr && (
							<img
								src={qr}
								alt="Your check-in code"
								className="
									w-full
									h-full
									object-contain
								"
							/>
						)}
					</div>
					<p className="
						font-beachday
						font-bold
						text-[17px]
						sm:text-[20px]
						text-salmon-med
						text-center
					">
						CLICK CARD TO FLIP BACK
					</p>
				</div>
			</div>
		</div>
	)
}
