// Longer write-ups for the seeded labs — about a hundred words each, so the
// member lab view's description block is as full as it is in the mockups.
// Kept apart from seed.js because they'd bury the fixture itself.
export const LAB_DESCRIPTIONS = {
    'Soap Bar': 'Learn the chemistry behind cold process soap, from saponification to curing. We will calculate a lye ratio for a blend of olive, coconut and shea, talk through why superfat matters for a gentle bar, and practise safe handling of sodium hydroxide with goggles and gloves on. You will mix, trace and pour your own loaf, then swirl in clays and botanicals for colour. Because cold process bars need four to six weeks to cure, you will take home a bar poured at the last session and leave today\'s loaf to harden for the next one.',
    'Bath Bomb': 'Why do bath bombs fizz, and why do some crumble while others hold their shape? This lab covers the acid-base reaction between citric acid and sodium bicarbonate, and how cornstarch, Epsom salt and a light oil change how fast it happens. We will compare witch hazel and water as binders, test how much moisture a mix can take before it starts reacting early, and press everything into moulds. Expect to play with mica colours, dried petals and skin-safe fragrance, and to leave with three bombs of your own plus notes on the ratios that worked best.',
    'Bronzer': 'Build a pressed powder bronzer from scratch. We start with the base — sericite, mica and silica — and look at what each one does for slip, glow and wear. Then we layer in iron oxides a drop at a time to reach a warm or cool shade that suits you, and talk about why a binder of oils and zinc stearate keeps the pan from crumbling. You will blend, sift, bind and press into a compact with a pressing die, then swatch against the rest of the room. Bring a brush if you have a favourite; we will provide everything else.',
    'Lipstick': 'Lipstick is a careful balance of waxes, oils and pigments, and today you get to find your own. We will compare candelilla, carnauba and beeswax for hardness and shine, see how castor oil disperses colour, and learn why pigments are ground into oil before they meet the wax. Everyone gets a small hot plate, a pipette set and a range of oxide and lake pigments to mix a custom shade. We will pour into metal moulds, flame the surface for a smooth finish and wind the bullets into tubes. You will also get a lab sheet to recreate your shade at home.',
    'Lip Gloss': 'This session is all about shine. We will work with a hydrogenated polyisobutene base, the ingredient that gives commercial gloss its cushiony, glassy finish, and see how adding a little castor oil or jojoba changes the feel. We will talk about micas versus pearls for shimmer, why some flavour oils sting, and how to keep a formula stable in a warm bag. You will make two tubes — one sheer and one pigmented — and swap with a partner to test wear. By the end you should be able to read the back of any gloss and know roughly what it is doing.',
    'Blush': 'Cream or powder? We make both and compare them side by side. For the cream, we melt a small batch of waxes and emollients, grind in red and pink pigments, and pour into pans to set. For the powder, we build on a talc-free base of sericite and silica, then press. Along the way we cover colour theory for cheeks, why certain pinks read orange on warm skin tones, and how to fix a blush that looks patchy. You will leave with one of each in your own shade, plus a mixing chart so you can adjust the recipe later without guessing.',
    'Body Butter': 'Body butter is an emulsion lesson in disguise. We will melt shea, cocoa and mango butters with a light carrier oil, cool the mix until it just starts to set, and whip it into a stiff, cloud-like cream. You will see why the temperature at which you whip decides whether you end up with fluff or grit, and how arrowroot powder cuts the greasy feel. We will also talk about preservatives: anhydrous products do not strictly need one, but a butter that meets wet hands does. Everyone takes home a jar, a scent they blended and notes on shelf life.',
    'Lip Scrub': 'A simple product with plenty of chemistry. We will look at why sugar exfoliates more gently than salt, how the grain size changes the feel, and which oils keep a scrub from drying out or separating in the jar. You will blend a base with coconut and sweet almond oils, add vitamin E as an antioxidant, and experiment with natural flavours like vanilla, peppermint and cocoa. We will cover what makes a flavour oil lip-safe and why citrus oils can irritate. By the end you will have two small tins of scrub and a clear idea of how to scale the recipe up.'
}
